### ISSUE TITLE
Well done!

### ISSUE THREAD

**Issue by eblanca** [cyxx/amazing_hod#1]
I see you've gone deep into the technical details, great!
Heart Of Darkness is an awesome game and it's nice to see others like it.
So, is this project going to be an engine recreation (as some comments suggest) or a resource explorer?

**Comment by cyxx** [comment]
Thanks.

I have the engine partially rewritten (allowing to move Andy in the first levels). The main task remaining is to reimplement the "monster" logic interpreter (the .mst file). Some wip video https://www.youtube.com/watch?v=hzaVl9yegLE

Not sure what this repository will evolve to, but for now, it is about extracting the resources.

I am closing this since that's not really an issue ;-)
